name = "studymate-client"
compatibility_date = "2024-01-01"

# Cloudflare Pages 설정
pages_build_output_dir = "dist"

# 환경 변수 (프로덕션)
[env.production]
[env.production.vars]
VITE_API_URL = "https://api.languagemate.kr"
VITE_WS_URL = "wss://api.languagemate.kr"
VITE_WORKERS_API_URL = "https://api.languagemate.kr"
VITE_WORKERS_WS_URL = "wss://api.languagemate.kr/ws"
VITE_WORKERS_BASE_URL = "https://api.languagemate.kr"

# 환경 변수 (프리뷰)
[env.preview]
[env.preview.vars]
VITE_API_URL = "https://api.languagemate.kr"
VITE_WS_URL = "wss://api.languagemate.kr"
VITE_WORKERS_API_URL = "https://api.languagemate.kr"
VITE_WORKERS_WS_URL = "wss://api.languagemate.kr/ws"
VITE_WORKERS_BASE_URL = "https://api.languagemate.kr"
