name = "studymate-client"
compatibility_date = "2024-01-01"

# Cloudflare Pages 배포 설정
[site]
bucket = "./dist"

[env.production]
name = "studymate-client-production"
route = { pattern = "languagemate.kr/*", zone_name = "languagemate.kr" }

[env.preview]
name = "studymate-client-preview"
route = { pattern = "preview.languagemate.kr/*", zone_name = "languagemate.kr" }

# 빌드 설정
[build]
command = "npm run build"
directory = "dist"

[build.environment]
NODE_VERSION = "18"

# 환경 변수 (프로덕션)
[env.production.vars]
VITE_API_URL = "https://api.languagemate.kr"
VITE_WS_URL = "wss://api.languagemate.kr/ws"

# 환경 변수 (프리뷰)
[env.preview.vars]
VITE_API_URL = "https://api-staging.languagemate.kr"
VITE_WS_URL = "wss://api-staging.languagemate.kr/ws"