name = "studymate-api-staging"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.staging]
name = "studymate-api-staging"
route = { pattern = "staging.studymate-api.workers.dev/*", zone_name = "workers.dev" }


# Durable Objects
[[env.staging.durable_objects.bindings]]
name = "ROOM"
class_name = "WebRTCRoom"
script_name = "studymate-api-staging"

# R2 Storage
[[env.staging.r2_buckets]]
binding = "STORAGE"
bucket_name = "studymate-storage-staging"

# KV Namespaces
[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "your-staging-kv-namespace-id"
preview_id = "your-staging-kv-preview-id"

# AI Bindings
[env.staging.ai]
binding = "AI"

# Environment Variables
[env.staging.vars]
ENVIRONMENT = "staging"
CORS_ORIGIN = "https://staging.studymate.com"
SCORING_MODE = "live"
EVAL_MODE = "live"
LEVEL_TEST_STUB = "false"

# Cloudflare Calls
[env.staging.calls]
binding = "CALLS"

# Analytics Engine
[[env.staging.analytics_engine_datasets]]
binding = "ANALYTICS"