name: Deploy Frontend (Cloudflare Pages)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build project
        run: npm run build
        env:
          VITE_API_URL: https://api.languagemate.kr
          VITE_WS_URL: wss://api.languagemate.kr/ws
          VITE_WORKERS_API_URL: https://api.languagemate.kr
          VITE_WORKERS_WS_URL: wss://api.languagemate.kr/ws
          VITE_NAVER_CLIENT_ID: ${{ secrets.VITE_NAVER_CLIENT_ID }}
          VITE_NAVER_REDIRECT_URI: https://languagemate.kr/login/oauth2/code/naver

      - name: Deploy to Cloudflare Pages (wrangler-action)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '4.28.1'
          # Deploy built assets in ./dist to Pages project 'studymate-client' as production (main)
          command: pages deploy dist --project-name=studymate-client --branch=main --commit-dirty=true