name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linter
        run: npm run lint
        
      - name: Build project
        run: npm run build
        env:
          VITE_API_URL: ${{ github.ref == 'refs/heads/main' && 'https://api.languagemate.kr' || 'https://api-staging.languagemate.kr' }}
          VITE_WS_URL: ${{ github.ref == 'refs/heads/main' && 'wss://api.languagemate.kr/ws' || 'wss://api-staging.languagemate.kr/ws' }}
          VITE_WORKERS_API_URL: ${{ github.ref == 'refs/heads/main' && 'https://workers.languagemate.kr' || 'https://workers-staging.languagemate.kr' }}
          VITE_WORKERS_WS_URL: ${{ github.ref == 'refs/heads/main' && 'wss://workers.languagemate.kr/ws' || 'wss://workers-staging.languagemate.kr/ws' }}
          VITE_NAVER_CLIENT_ID: ${{ secrets.VITE_NAVER_CLIENT_ID }}
          VITE_NAVER_REDIRECT_URI: ${{ github.ref == 'refs/heads/main' && 'https://languagemate.kr/login/oauth2/code/naver' || 'https://preview.languagemate.kr/login/oauth2/code/naver' }}
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: studymate-client
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref == 'refs/heads/main' && 'production' || github.head_ref || 'preview' }}
          
      - name: Comment PR with preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = context.payload.pull_request.head.ref;
            const previewUrl = `https://${branch}.studymate-client.pages.dev`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Preview URL**: ${previewUrl}\n\n✅ Build and deployment successful!`
            });